### ISSUE TITLE
Add a bioconda package

### ISSUE THREAD

**Issue by oschwengers** [BolognaBiocomp/deepsig#20]
Following up on #15 I've started to create a PR to add a DeepSig conda package to Bioconda:
https://github.com/bioconda/bioconda-recipes/pull/28278

I forgot to mention, in order to create such a conda package we also need a proper Git release.
Could you therefor please create a proper `v1.0` release for this DeepSig repo? It's common best practices anyway, so that users can relate to a certain version of a software.

**Comment by savojard** [comment]
done!

**Comment by oschwengers** [comment]
thanks! I'm going ahead ...

**Comment by oschwengers** [comment]
Just wanted to leave a short note that it might take a while to get this done but we still have this on our list and we're keen to work on this.
There's a PR on BioConda: https://github.com/bioconda/bioconda-recipes/pull/28278

**Comment by oschwengers** [comment]
All things back - I just managed to get it working in conda. The PR is still open and needs a 3rd party review but both CI and local manual tests are working fine.

**Comment by oschwengers** [comment]
Ok - it's done!
Please have a look here: https://anaconda.org/bioconda/deepsig
I'll close this for now.
